name: README update

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Get Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Show Python version
        run: python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update README and SVGs
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: python update_readme.py
      - name: Commit SVG and README changes
        run: |-
          git add README.md docs/dark_mode.svg docs/light_mode.svg
          git diff --cached
          git config --global user.email "github-actions-bot@msadeqsirjani.github.io"
          git config --global user.name "msadeqsirjani/GitHub-Actions-Bot"
          git commit -m "Automated update: README and SVG stats" || echo "No changes to commit"
          git push
