name: README update

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Get Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install python-dateutil requests
      - name: Update README file
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: python update_readme.py
      - name: Commit
        run: |-
          git add .
          git diff
          git config --global user.email "github-actions-bot@msadeqsirjani.github.io"
          git config --global user.name "msadeqsirjani/GitHub-Actions-Bot"
          git commit -m "update: README.md" -a || echo "No changes to commit"
          git push
